name: ip_geolocation_api
description: Un package dart
version: 0.0.1
author: PABLO FIRULO
homepage: https://pf.uy

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.12.2
  meta: ^1.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

